# https://taskfile.dev
version: '2'
tasks:

  hi:
    cmds:
      - python hello.py
  py:
    cmds:
    - python
      
  doctest:
    cmds:
      - python tests/test_doctest.py
  pytest:
    cmds:
      - py.test
      # - py.test tests/modtry
  t:
    cmds:
      - task: pytest

  t1:
    cmds:
      - python tests/unittest/test_sum.py
  t2:
    cmds:
      # - pytest tests/pytest/test_sum.py
      - pytest tests/pytest/test_sum.py::test_sum
  t3:
    cmds:
    - |
      cd tests/layout_demo
      task default
  t4:
    cmds:
    # python -m unittest -v to-test-module
    - |
      cd tests/unittest
      python -m unittest discover
      # python -m unittest discover -s tests -t src

  setup:
    cmds:
      # pip freeze > requirements.txt
      # pip install -r requirements.txt
      
      - pipenv install
      # To activate this project's virtualenv, run pipenv shell.
      # Alternatively, run a command inside the virtualenv with pipenv run

  ubase:
    cmds:
      - python -m site --user-base
  version:
    cmds:
      - |
        # python --version
        python -V
        python2 -V
        python3 -V

  install-pytest:
    cmds:
      - pip install pytest
      - pytest --version

  install-python3:
    desc: https://docs.brew.sh/Homebrew-and-Python
    cmds:
      - brew install python
      - brew info python
      - python3 -V
      - pip --version
      # - ls -l /usr/local/opt/python@3.8/libexec/bin
      # Python has been installed as
      #   /usr/local/bin/python3
      
      # You can install Python packages with
      #   pip3 install <package>
      # They will install into the site-package directory
      #   /usr/local/lib/python3.8/site-packages

  install-pipenv:
    desc: install pipenv like bundler, npm
    cmds:
    - pip install --user pipenv

  macos-builtin-python:
    cmds:
    - ls -l /System/Library/Frameworks/Python.framework/Versions/
    # - which python # 2.7